// portfolio-nuxt-migration/app/app.vue
<template>
  <div class="min-h-screen bg-white">
    <NuxtRouteAnnouncer />
    <Navigation />
    <main>
      <Hero />
      <Skills />
      <Projects />
      <Experience />
      <Contact />
    </main>
    <footer class="bg-white text-gray-500 py-8 border-t border-gray-100">
      <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <p class="text-sm">© 2026 出口 史亜. All rights reserved.</p>
      </div>
    </footer>
  </div>
</template>

// src/App.tsx
import { Navigation } from './components/Navigation';
import { Hero } from './components/Hero';
import { Skills } from './components/Skills';
import { Projects } from './components/Projects';
import { Experience } from './components/Experience';
import { Contact } from './components/Contact';

export default function App() {
  return (
    <div className="min-h-screen bg-white">
      <Navigation />
      <main>
        <Hero />
        <Skills />
        <Projects />
        <Experience />
        <Contact />
      </main>
      <footer className="bg-white text-gray-500 py-8 border-t border-gray-100">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <p className="text-sm">© 2026 出口 史亜. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
